# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2023.11.17
_src_path: gh:scientific-python/cookie
backend: hatch
email: nstarman@users.noreply.github.com
full_name: Nathaniel Starkman
license: BSD
org: GalacticDynamics
project_name: quaxed
project_short_description:
  Pre-quaxed libraries for multiple dispatch over abstract array types in JAX
url: https://github.com/GalacticDynamics/quaxed
vcs: true
